name: size

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  size:
    name: 'PR #${{ github.event.number }}: Check Size Limit'
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - name: Check Size-Limit
        uses: andresz1/size-limit-action@v1.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: pre-size
          skip_step: install
          # script: yarn run size
